.\" manpage for pyplatform
.\" contact me at thespokenone209@hotmail.com for issues.
.\" nacroni - fyi the name for default stuff is General Commands Manual
.TH pyplatform 1 "5 Dec 2024" "main Branch" "pyplatform Manual"

.SH NAME
.B pyplatform 
- a command to get platform information

.SH SYNOPSIS
.B pyplatform 
[ -h ] [ --help ] [ -f ] [ --freedesktop ] [ -w ] [ --win32 ] [ -m ] [ --mac ]

.SH DESCRIPTION
.B pyplatform
is a Python script that shows information about your current system using the platform module.

.SH EXAMPLES
.B pyplatform

.B pyplatform
-wfm /
.B pyplatform
--win32 --freedesktop --mac

.B pyplatform
-h /
.B pyplatform
--help

.SH COMMAND LINE OPTIONS

.SS -h, --help
Shows help and exits

.SS -f, --freedesktop
Shows freedesktop.org OS release information (JSON) in the normal output

.SS -w, --win32
Shows win32 information in the normal output

.SS -m, --mac
Shows macOS information in the normal output

.SH AUTHOR
.SS Owner / Creator
Nacroni - E-Mail: thespokenone209@hotmail.com

.SH COPYRIGHT
GPLv3 License, can be found in the source repo as 
.B LICENSE.md

Or you can find the license's current version online at 
.ul
https://www.gnu.org/licenses/gpl-3.0.en.html
.

Thank you, and have a very safe day.
